name: gyro_provider
description: A plugin that provides data from gyroscopes and rotation sensors and related handy widgets.
version: 0.1.0
homepage: https://wjlee611.github.io/
repository: https://github.com/wjlee611/gyro_provider

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gmail.wjlee611.gyro_provider
        pluginClass: GyroProviderPlugin
      ios:
        pluginClass: GyroProviderPlugin
